// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form': string;
  'formLabel': string;
  'input': string;
  'inputMin': string;
  'tag': string;
  'tagAdd': string;
  'tagBtn': string;
  'tagLabel1': string;
  'tagLabel2': string;
  'tagRemove': string;
}
export const cssExports: CssExports;
export default cssExports;
