// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    applyBtn: string;
    btnContainer: string;
    cellBox: string;
    current: string;
    goodsImg: string;
    icon: string;
    link: string;
    new: string;
    paginationWrapper: string;
    tabs: string;
}
export const cssExports: CssExports;
export default cssExports;
