// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'desc': string;
  'filterSection': string;
  'goodsInfo': string;
  'inputWrap': string;
  'label': string;
  'link': string;
  'mainImg': string;
  'popTable': string;
  'skuContent': string;
  'skuImg': string;
  'table': string;
  'tagBtn': string;
}
export const cssExports: CssExports;
export default cssExports;
