// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bg': string;
  'btn': string;
  'btnActive': string;
  'tick': string;
}
export const cssExports: CssExports;
export default cssExports;
