// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    btn: string;
    chartSection: string;
    container: string;
    formSection: string;
    item: string;
    jumpSection: string;
    operationBox: string;
    title: string;
}
export const cssExports: CssExports;
export default cssExports;
