// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'affix': string;
  'chartSection': string;
  'container': string;
  'coreDataTitle': string;
  'dateSection': string;
  'decrease': string;
  'first': string;
  'formSection': string;
  'increase': string;
  'periodSection': string;
  'secondLine': string;
  'statistic': string;
  'summaryBox': string;
  'summaryItem': string;
  'table': string;
  'tableSection': string;
  'totalSection': string;
  'variousBox': string;
}
export const cssExports: CssExports;
export default cssExports;
