// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btns': string;
  'flex': string;
  'img': string;
  'imgItem': string;
  'imgLabel': string;
  'item': string;
  'label': string;
  'list': string;
  'modalContent': string;
  'upload': string;
  'uploadDesc': string;
}
export const cssExports: CssExports;
export default cssExports;
