// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    btnGo: string;
    btnGroup: string;
    btnGutter: string;
    btnLink: string;
    btnSilver: string;
    btnWithoutAnim: string;
}
export const cssExports: CssExports;
export default cssExports;
