// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    channelExportModal: string;
    channelImg: string;
    channelShipModal: string;
    logContent: string;
    logModal: string;
}
export const cssExports: CssExports;
export default cssExports;
