// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    exportAction: string;
    exportCard: string;
    exportCardContent: string;
    exportClose: string;
    exportDate: string;
    exportError: string;
    exportErrorIcon: string;
    exportErrorText: string;
    exportIcon: string;
    exportIconWrap: string;
    exportProgress: string;
    exportProgressLabel: string;
    exportSize: string;
    exportTotal: string;
}
export const cssExports: CssExports;
export default cssExports;
