// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    block: string;
    clip: string;
    container: string;
    fill: string;
    hide: string;
    inlineBlock: string;
    marginNone: string;
    none: string;
    relative: string;
    textCenter: string;
    textEllipse: string;
    textRight: string;
    transparent: string;
    verticalMiddle: string;
}
export const cssExports: CssExports;
export default cssExports;
