// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    merchantModal: string;
    merchantModalContent: string;
}
export const cssExports: CssExports;
export default cssExports;
