// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkedIcon': string;
  'cookieColumn': string;
  'cookieColumnContent': string;
  'uncheckedIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
