// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'absBtn': string;
  'afterItem': string;
  'disable': string;
  'formAsLabel': string;
  'goodImg': string;
  'labelSelect': string;
  'priceAfter': string;
  'purchaseInput': string;
  'refresh': string;
  'right': string;
  'select': string;
  'selectType': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
