// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    errorIcon: string;
    errorText: string;
    failureSuffixIcon: string;
    progressIcon: string;
    progressText: string;
    successIcon: string;
    successText: string;
    taskDetailCard: string;
    taskDetailContent: string;
    taskIdsSelect: string;
    taskModal: string;
    taskStatusText: string;
    waitIcon: string;
    warnIcon: string;
}
export const cssExports: CssExports;
export default cssExports;
