// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    container: string;
    extra: string;
    flex: string;
    gutter: string;
    noneMargin: string;
    second: string;
    select: string;
    title: string;
}
export const cssExports: CssExports;
export default cssExports;
