// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'formItem': string;
  'formLabel': string;
  'formPicker': string;
}
export const cssExports: CssExports;
export default cssExports;
