// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    copyIcon: string;
    copyTip: string;
    fixedWidgets: string;
}
export const cssExports: CssExports;
export default cssExports;
