// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    content: string;
    gather: string;
    header: string;
    image: string;
    key: string;
    modal: string;
    modalContent: string;
    name: string;
    order: string;
    title: string;
    title1: string;
    typeError: string;
}
export const cssExports: CssExports;
export default cssExports;
