# trigram-scm-front-page
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trigram-scm-front-page-nginx-conf-prod
data:
  nginx.conf: |
    user  www-data;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format apache_format escape=json
          '{"remote_addr":"$remote_addr",'
          '"remote_user":"$remote_user",'
          '"time_local":"$time_local",'
          '"request":"$request",'
          '"status":$status,'
          '"body_bytes_sent":$body_bytes_sent,'
          '"http_referer":"$http_referer",'
          '"http_user_agent":"$http_user_agent",'
          '"http_x_forwarded_for":"$http_x_forwarded_for",'
          '"host":"$host",'
          '"upstream_cache_status":"$upstream_cache_status",'
          '"request_time":$request_time}';


        access_log  /var/log/nginx/access.log  apache_format;
        sendfile        on;
        #tcp_nopush     on;
        keepalive_timeout  120;
        gzip on;
        gzip_http_version 1.0;
        gzip_proxied any;
        gzip_min_length  1100;
        gzip_buffers     4 8k;
        gzip_types       text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript image/x-icon application/javascript;
        gzip_vary on;
        client_max_body_size 20m;
        include /etc/nginx/conf.d/*.conf;
    }
  trigram-scm-front-page.conf: |
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        access_log  /var/log/nginx/access.log  apache_format;
        set $prjroot /usr/share/nginx/html;
        root $prjroot/;
        index index.html;
        location /version {
            root $prjroot/;
            add_header Content-Type text/plain;
        }

        location ~.*\.(js|css|png|jpg)$
        {
            expires 30d;
            try_files $uri $uri/ /index.html;
        }

        location / {
            if ($cookie_jsessionid = "")
            {
                return 302 https://cas.vova.com.hk/cas/login?service=https://${host}/auth/cas_login;
            }
            try_files $uri $uri/ /index.html;
        }
        location /auth/{
            proxy_set_header   Cookie $http_cookie;
            proxy_set_header   Host $host;
            proxy_set_header   Remote_Addr $remote_addr;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   REMOTE-HOST $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass https://scm-api.vova.com.hk;
            }
        location /api/{
            add_header Access-Control-Allow-Origin *;
            rewrite ^/api(.*)$ /$1 break;
            proxy_set_header   Cookie $http_cookie;
            proxy_set_header   Host $host;
            proxy_set_header   Remote_Addr $remote_addr;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   REMOTE-HOST $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass https://scm-api.vova.com.hk/;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trigram-scm-front-page-prod
  labels:
    name: trigram-scm-front-page-prod
spec:
  selector:
    matchLabels:
      name: trigram-scm-front-page-prod
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: trigram-scm-front-page-prod
      labels:
        name: trigram-scm-front-page-prod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: trigram-scm-front-page
          image: 512358210769.dkr.ecr.us-east-1.amazonaws.com/scm-front:page-prod
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http-port
          volumeMounts:
            - name: trigram-scm-front-page-conf-prod
              mountPath: /etc/nginx/conf.d
            - name: nginx-conf-prod
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-log-prod
              mountPath: /var/log/nginx
          livenessProbe:
            httpGet:
              path: /version
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /version
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12
      volumes:
        - name: nginx-log-prod
          hostPath:
            path: /opt/data1/logs/scm-front/nginx
        - name: nginx-conf-prod
          configMap:
            name: trigram-scm-front-page-nginx-conf-prod
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: trigram-scm-front-page-conf-prod
          configMap:
            name: trigram-scm-front-page-nginx-conf-prod
            items:
              - key: trigram-scm-front-page.conf
                path: trigram-scm-front-page.conf
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - trigram-scm-front-page-prod
                topologyKey: kubernetes.io/hostname

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: trigram-scm-front-page-svc
#  annotations:
#    alb.ingress.kubernetes.io/healthcheck-path: /version
#spec:
#  selector:
#    name: trigram-scm-front-page
#  ports:
#    - name: entry
#      port: 80
#      targetPort: 80
#      protocol: TCP
#  type: NodePort

## 使用下面的配置alb controller会再创建一个alb
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: aws-alb-scm-front
#  annotations:
#    kubernetes.io/ingress.class: alb
#    alb.ingress.kubernetes.io/scheme: internet-facing
#    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-2016-08
#    alb.ingress.kubernetes.io/certificate-arn:  arn:aws:acm:us-east-1:832373879023:certificate/3f84bac5-ca0d-48a0-8da2-f4b9f7d1d03f
#    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS":443}]'
#    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
#    alb.ingress.kubernetes.io/success-codes: '200,302'
#    alb.ingress.kubernetes.io/security-groups: 'sg-00f93e4d234a5ca8b'
#    alb.ingress.kubernetes.io/subnets: 'subnet-4eef3b61,subnet-2064f56b,subnet-b31bd2ee'
#spec:
#  rules:
#    - host: schain-t.vova.com.hk
#      http:
#        paths:
#          - backend:
#              serviceName: ssl-redirect
#              servicePort: use-annotation
#          - path: /*
#            backend:
#              serviceName: trigram-scm-front-page-svc
#              servicePort: 80


---
kind: Service
apiVersion: v1
metadata:
  name: trigram-scm-front-page-external-prod-elb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:512358210769:certificate/cc03a721-5f47-4cec-95ed-bcba97e46952
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: sg-0ac24f3c90dd52e38
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "120"
spec:
  selector:
    name: trigram-scm-front-page-prod
  ports:
    - name: svc-http
      port: 80
      targetPort: http-port
      protocol: TCP
    - name: svc-https
      port: 443
      targetPort: http-port
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 180.167.146.154/32
    - 140.206.96.158/32
    - 58.247.99.18/32
    - 116.228.132.228/32
    - 180.169.144.154/32
    - 180.168.193.50/32
    - 45.117.98.16/32 #11楼专线
