// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    good: string;
    image: string;
    sku: string;
    skuKey: string;
    skus: string;
    title: string;
}
export const cssExports: CssExports;
export default cssExports;
