// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    abnormalModal: string;
    cascaderBox: string;
    checkbox: string;
    desc: string;
    detailModal: string;
    disabled: string;
    edit: string;
    form: string;
    goodsInfo: string;
    icon1: string;
    icon2: string;
    icon3: string;
    iconBox: string;
    iconSection: string;
    img: string;
    imgCell: string;
    inputNumber: string;
    itemBox: string;
    label: string;
    line: string;
    lineOne: string;
    lineTwo: string;
    name: string;
    number: string;
    numberBox: string;
    one: string;
    red: string;
    relatedBox: string;
    remark: string;
    sectionBox: string;
    select: string;
    stepOne: string;
    styleItem: string;
    tableFormItem: string;
    title: string;
    two: string;
}
export const cssExports: CssExports;
export default cssExports;
