// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    address: string;
    amount: string;
    connectInput: string;
    connectLabel: string;
    formItem: string;
    formItemMl: string;
    formLabel: string;
    formRight: string;
    image: string;
    paragraph: string;
    productDesc: string;
    title: string;
}
export const cssExports: CssExports;
export default cssExports;
