// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'formInput': string;
  'formItem': string;
  'formLabel': string;
  'formLabelDisabled': string;
  'formTextarea': string;
  'image': string;
  'justifyCenter': string;
  'modalImage': string;
  'modalSku': string;
  'modalSkuValue': string;
  'modalSkus': string;
  'modalTitle': string;
  'paragraph': string;
  'productDesc': string;
  'steps': string;
  'textCenter': string;
}
export const cssExports: CssExports;
export default cssExports;
