// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'breadcrumb': string;
  'menu': string;
  'right': string;
  'user': string;
}
export const cssExports: CssExports;
export default cssExports;
