// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnAdd': string;
  'btnSave': string;
  'loadingContainer': string;
  'opsContainer': string;
  'pagination': string;
  'paginationContainer': string;
  'tableContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
