export enum ChannelApiPath {
    QueryProductList = '/api/v1/vova_goods/list',
    QueryCategory = '/api/v1/vova_goods/catagory/list',
    QueryChangedProperties = '/api/v1/vova_goods/changed_property',
    UpdateShelveState = '/api/v1/vova_goods/sales',
    ExportProductList = '/api/v1/vova_goods/exports',
    QueryProductVersion = '/api/v1/vova_goods/version_list',
    QueryProductDetail = '/api/v1/vova_goods/detail',
    EditProductDetail = '/api/v1/vova_goods/edits',
    CleanChangedProperties = '/api/v1/vova_goods/readed_property',
    ExportProductVersion = '/api/v1/vova_goods/version_exports',
    ActiveProductVersion = '/api/v1/vova_goods/apply_version',
    QueryRegionShippingFee = '/api/v1/vova_goods/region_shipping_fee',
    QueryGoodsDetail = '/api/v1/vova_goods/detail',
    QueryGoodsSkuList = '/api/v1/vova_goods/sku_list',
    EditSkuPrice='/api/v1/vova_goods/edits',
}
