export enum PriceStrategyApiPath {
    getTagsList = '/api/v1/tags/list',
    getSalePriceList = '/api/v1/price_strategy/list_sale_price_rule',
    saveSalePriceRule = '/api/v1/price_strategy/sale_price_rule_save',
    getShippingCardNameList = '/api/v1/price_strategy/shipping_card_name_list',
    getShippingCardCountry = '/api/v1/price_strategy/shipping_card_country',
    getShippingCardList = '/api/v1/price_strategy/list_shipping_card',
    saveShippingCard = '/api/v1/price_strategy/shipping_card_save',
    getShippingFeeRuleList = '/api/v1/price_strategy/list_shipping_fee_rule',
    saveShippingFeeRule = '/api/v1/price_strategy/shipping_fee_rule_save',
    startPriceStrategyUpdate = '/api/v1/price_strategy/rule_update',
    getCatagoryWeightList = '/api/v1/price_strategy/category_weight_list',
    saveCatagoryWeight = '/api/v1/price_strategy/category_weight_save',
    getCatagoryWeightLog = '/api/v1/price_strategy/category_weight_log',
    getSaleAndShippingOperateLog = '/api/v1/price_strategy/rule_operate_log',
    getShippingFeeRuleConfig = '/api/v1/price_strategy/get_shipping_fee_rule',
    getSalePriceRuleConfig = '/api/v1/price_strategy/get_sale_price_rule',
    getShippingCartDetail = '/api/v1/price_strategy/get_shipping_card',
}
