/**
 * 设置页面Api字典
 */
export enum SettingApiPath {
    QueryCustomDeclarationList = '/api/v1/customs/list',
    QueryCountryList = '/api/v1/customs/country',
    UpdateCustom = '/api/v1/customs/put',
    QueryCookie = '/api/v1/spider/account/list',
    UpdateCookie = '/api/v1/spider/account/update',
    ExportList = '/api/v1/download/list',
    RetryExport = '/api/v1/download/repeat',
    DeleteExport = '/api/v1/download/delete',
    UpdateExport = '/api/v1/download/detail',
    QueryPriceStrategy = '/api/v1/price_strategy/detail',
    UpdatePriceStrategy = '/api/v1/price_strategy/store',
    QueryPriceStrategyHistory = '/api/v1/price_strategy/history',
    // 线下采购配置
    QueryOfflinePurchaseList = '/api/v1/orders/setting/purchase/offline/list',
    QueryOfflinePurchaseInfo = '/api/v1/orders/setting/purchase/offline/:id',
    AddOfflinePurchase = '/api/v1/orders/setting/purchase/offline',
    UpdateOfflinePurchase = '/api/v1/orders/setting/purchase/offline/:id',
    DelOfflinePurchase = '/api/v1/orders/setting/purchase/offline/:id',
    QueryReplaceList = '/api/v1/orders/setting/delivery/replace/list',
    DeleteReplaceList = '/api/v1/orders/setting/delivery/replace/{id}',
    AddReplaceList = '/api/v1/orders/setting/delivery/replace',
    EditReplaceList = '/api/v1/orders/setting/delivery/replace/{id}',
    QueryReplace = '/api/v1/orders/setting/delivery/replace/{id}',
    // 采购店铺黑名单
    getStoreBlacklist = '/api/v1/strategy/black_store_list',
    saveBlackStore = '/api/v1/strategy/black_store_save',
    deleteBlackStore = '/api/v1/strategy/black_store_delete',
    // 订单审核配置
    QueryOrderConfigList = '/api/v1/orders/config/list',
    AddOrderConfig = '/api/v1/orders/config/save_config',
    DelOrderConfig = '/api/v1/orders/config/delete_config',
    queryAccountList = '/api/v1/users/list',
    addAccount = '/api/v1/users',
    queryPermissionTree = '/api/v1/auth/list',
    updateAccount = '/api/v1/users/modify/{id}',
    queryAccount = '/api/v1/users/{id}',
    queryRoleList = '/api/v1/roles/list',
    addRole = '/api/v1/roles',
    editRole = '/api/v1/roles/modify/{id}',
    queryAccountCreator = '/api/v1/users/get_create_user/{type}',
    queryRolePermission = '/api/v1/roles/auth/{role_ids}',
    deleteRole = '/api/v1/roles/delete/{id}',
    updateRoleStatus = '/api/v1/roles/freeze/{id}',
    updateAccountStatus = '/api/v1/users/{id}',
}
