// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnContainer': string;
  'calc': string;
  'calcContainer': string;
  'cancel': string;
  'customLabel': string;
  'extra': string;
  'flex': string;
  'formContainer': string;
  'gutter': string;
  'hover': string;
  'inputNumber': string;
  'item': string;
  'itemMargin': string;
  'multipleSelect': string;
  'noneMargin': string;
  'paneContent': string;
  'select': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
