// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnSave': string;
  'download': string;
  'extra': string;
  'filename': string;
  'iconClose': string;
  'iconFile': string;
  'input': string;
  'item': string;
}
export const cssExports: CssExports;
export default cssExports;
